#+TITLE:Development Notes
* Introduction :TOC:
- [[#progress][Progress]]
- [[#development][Development]]
  - [[#research][Research]]
  - [[#structure-notes][Structure Notes]]

* Progress
Not much at this stage.

* Development

** Research
Programs in /research/ are used to implement, test and evaluate 
various parts of the program.

- /xtank-dlopen/ :: Compile and load a separate program (using *dlopen*), used for
  implementing additional modules. (eg. robot programs, HUD improvements)

- /example-dlopen/ :: A *dlopen* example.

- /example-dlopen/ :: A *gmodule* example. GModule 2.0 is the Portable GLib API for
  dynamically loading modules. 

** Structure Notes

*** General Comments
The following are some idisyncratic features of the xtank code from the original
authors. Not quite easter eggs.

- rorre() :: Function used when getting an error and program can't continue.
  Macro defined in [[src/include/common.h:74]]

- #ifdef REALLY_RUDE :: Only one instance, but adds an additional help message. 

*** Notes
- (CLFkr) ConfigRunning, command_options :: Structure used to contain
  configuration. Initially stored in *command_options* in main.c, with settings
  loaded from command line options. Defined in *clfkr.h*

#+begin_src C 
  Boolean AutoExit;	 // Exit immediately after running
  Boolean AutoStart;	 // Skip the main menu and begin
                       // execution automatically?
  Boolean UseSetting;	 // Use a settings file specified
                       // on the command line?
  Boolean PrintScores; // Print scores to standard out after
                       // running a game?
  char *Settings;		 // File from which to load settings.
  Boolean NoDelay;	 // Skip all pauses during gameplay?
  Boolean NoIO;		 // Skip all screen I/O?
#+end_src

- (BSet) bset :: Bullet Set - structure containing data of current bullets in an
  array, and an array/list of pointers to these bullets. *MAX_BULLETS* defined in
  *tanklimits.h.*
  
- (Eset) eset :: Explosion Set - similar structure to handle bullets. *MAX_EXPS*
  defined in *tanklimits.h*.

- (Maze) maze :: Structure which stores vehicle starting location (*Coord*), by
  team. Defined in maze.h.

- Vehicle Arrays :: *actual_vehicles*, **live_vehicles*, **dead_vehicles*, num_veh,
  num_veh_alive, num_veh_dead. The arrays live_vehicles, dead_vehicles are
  pointers into the *actual_vehicles*. Permanently 'dead' vehicles leave holes in
  *actual_vehicles*.

Game Grid - MAX_GRIDS x MAX_VEHICLES
- grid_entries[] :: Array of column name in game grid
- (Byte) grid_val[][] ::
- (char *) grid_ent[][] ::
- (int) grid_id[] ::
  
- players_entries ::
- vehicles_entries ::
- teams_entries ::
  
*** Defines(includes)
- xtank.h :: Contains a bunch of useful defines. (Includes screen.h, vdesc.h,
  xtanklib.h)

  What are TEST_TURRENTS?

- proto.h :: Function prototypes. In the original code this header file
  contained all of the function prototypes for files except for *lowlib*, *highlib*
  (in lowlib).

  Uses a macro *P_* to remove additional parenthesis in the declarations. Why?

  #+begin_src C
#if 1 || defined(__STDC__) || defined(__cplusplus)
#define P_(s) s
#else
#define P_(s) ()
#endif
#+end_src

- maze.h :: Data structures for storing descriptive maze information. Requires
  'teams.h', 'tanklimits.h' to be defined first as it uses *MAX_TEAMS*,
  *MAX_VEHICLES*.

*** Initialisation
- init_changed_boxes :: Should be called at the beginning of each frame

- set_terminal() :: Set's the current terminal number.

- get_player_info() :: Prompt a player for their name, and vehicle name (which
  needs to exist).
  
*** Main Menu Loop (interface.c)
- main_interface(void) :: Called from main.c to start program. Declared in *proto.h*, defined in *interface.c.*
- set_terminal(0) ::
- init_interface() ::

- fix_combantants(i) (SIC) :: Put player into game grid. Uses *grid_ent*, *grid_val,*
  *players_entries*, *vehicles_entries*, *teams_entries*.

- button_up() ::
- follow_mouse() ::
- display_file() ::
- display_title() ::
- display_settings() ::

- win_exposed() ::
- get_events() :: Get events to process in main event loop.

- menu_hit() ::
- erase_other_menus() :: 
- menu_hit_p() :: Return menu choice by comparing event location (ev.x, ev.y).

- sub_interface_main() ::
- sub_interface_main() ::
- sub_interface_load() ::
- sub_interface_design() ::
- sub_interface_help() ::
- display_settings() ::
- menu_unhighlight() ::
- remove_player() ::
- expose_win() ::
- do_view() ::
- sub_interface_machine() ::
- sub_interface_play() :: See game loop
- sub_interface_settings() ::
- sub_interface_flags() ::
- sub_interface_force() ::
    
- menu_display(Menu_int *menuobj, int menuid) ::  

*** Game Loop
- sub_interface_play() :: Choose the type of game to start. Standard, player,
  robots or customize.

- standard_combatants() ::
- player_combatants() ::
- robot_combatants() ::
- customized_combatants() ::
- interface_play() ::
- menu_unhighlight() ::
