#+TITLE: XTank for GTK4

* Introduction

This project is currently a *Work in Progres* (WIP) so if anything that you find
here is useful, then please let me know.

The code is being ported to run on Linux, and specifically Ubuntu.

The original code-base builds and runs on a wide range of architectures and with
a range of compilers. These dependencies on the various architectures are
dispersed among the source files with various 'defines' used to switch between
the compiled code.

The way that progress can be made is to target a single platform, hopefully in a
clean way, that can be then ported in a straight forward manner to other
platforms if required.

* Development

** Research
Programs in /research/ are used to implement, test and evaluate 
various parts of the program.

- /xtank-dlopen/ :: Compile and load a separate program (using *dlopen*), used for
  implementing additional modules. (eg. robot programs, HUD improvements)

- /example-dlopen/ :: A *dlopen* example.

- /example-dlopen/ :: A *gmodule* example. GModule 2.0 is the Portable GLib API for
  dynamically loading modules. 

* Building

#+begin_src shell
  cd src
  make
#+end_src

* Progress
Not much at this stage.

* Structure
